import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionProvider from '../components/SessionProvider'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; 
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <main className="p-5">
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
